version: '3'
services:
  ruby:
    container_name: 'ruby'
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: '/root/app/src'
    tty: true
    volumes:
      - ./app:/root/app
  xunit:
    container_name: 'xunit'
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: '/root/xunit'
    tty: true
    volumes:
      - ./xunit:/root/xunit
